### ISSUE TITLE
node.style should not be used to check if an element is hidden

### ISSUE THREAD

**Issue by xi** [WhatSock/w3c-alternative-text-computation#1]
In this example, the link is not hidden, but the sample implementation will still ignore it:

```html
<style>
a {
	display: initial !important;
}
</style>

<a style="display: none">test</a>

```

**Comment by accdc** [comment]
Thanks, I see what you mean, but are you aware of a cross-browser compatible JS technique that can detect when this is the case? E.G when style is not taking precedence in such a case as this, except when it is? Admittedly multi-layered CSS rendering processes are difficult for me to test for at times.

**Comment by xi** [comment]
> are you aware of a cross-browser compatible JS technique that can detect when this is the case?

I think just using `getComputedStyle` and maybe `currentStyle` as a fallback for old IEs should be sufficient.

**Comment by xi** [comment]
I mistakenly marked f8e4ad3 as fixing this. This is actually still an issue.

**Comment by accdc** [comment]
Thanks, this is still on my todo list, along with nested labels and embedded controls that support value properties.

**Comment by xi** [comment]
Can you please re-open this issue?

**Comment by accdc** [comment]
Hi, with the rewrite there is no call to the style object on the node, so this issues should be fixed.
