### ISSUE TITLE
No name from content for row/rowgroup

### ISSUE THREAD

**Issue by xi** [WhatSock/w3c-alternative-text-computation#14]
According to [ARIA](https://www.w3.org/TR/wai-aria/#row), the name for a row (and also rowgroup) should be computed from its contents. The implementation fails to do that:

https://xi.github.io/babelacc/?input=%3Cdiv+role%3D%22row%22%3Efoo%3C%2Fdiv%3E

**Comment by joanmarie** [comment]
We removed `rowgroup` because that results in some potentially verbose and confusing "names". See the current Editors Draft: https://w3c.github.io/aria/#rowgroup.

**Comment by accdc** [comment]
I'll look into row if that is presently missing.

**Comment by accdc** [comment]
Hi,
This is now corrected.
https://whatsock.github.io/w3c-alternative-text-computation/Editable%20Live%20Input%20AccName%20Test.html

Example markup:

```
<div role="table">
<div role="row" id="test">
<div role="cell">
<span>Cell Text</span>
</div>
</div>
</div>
```

**Comment by accdc** [comment]
Hi,
As of version 2.22, the AccName Prototype now uses name from content for role=row, but not for role=rowgroup, since 'name from content' is in the processed of being removed from role=rowgroup in the ARIA spec.

**Comment by jimmyjamesss** [comment]
Is W3.com or W3c.com loaded on my phone.  What I read up on it’s to help out the disabled. Special software for them.  Could it be used as spying software?
