### ISSUE TITLE
Whitespace not based on actual styling

### ISSUE THREAD

**Issue by xi** [WhatSock/w3c-alternative-text-computation#15]
Is it intentional that the whitespace is added based on initial instead of actual styling? Consider the following example:

```
<button>
  <h1 style="display:inline">foo</h1><h1 style="display:inline">bar</h1>
</button>
```

https://xi.github.io/babelacc/?input=%3Cbutton%3E%0D%0A++%3Ch1+style%3D%22display%3Ainline%22%3Efoo%3C%2Fh1%3E%3Ch1+style%3D%22display%3Ainline%22%3Ebar%3C%2Fh1%3E%0D%0A%3C%2Fbutton%3E

I would expect there to be no whitespace since both elements are styled as inline. However, this implementation adds whitespace.

**Comment by accdc** [comment]
Hi,
Thanks, yes indeed, it should be treating this as inline, so I'll add this to be fixed soon.

**Comment by accdc** [comment]
Hi,
This is now corrected.
https://whatsock.github.io/w3c-alternative-text-computation/Editable%20Live%20Input%20AccName%20Test.html

Example markup:

```
<button id="test">
  <h1 style="display:inline">foo</h1><h1 style="display:inline">bar</h1>
</button>
```

**Comment by xi** [comment]
Awesome. Thanks for the quick reply!
