### ISSUE TITLE
progress element lacks acc name even with label for in play

### ISSUE THREAD

**Issue by chrisblouch** [WhatSock/w3c-alternative-text-computation#20]
Testing out this markup:
```
<label for="test">Some Text</label>
<progress id="test" max="100" value="33"></progress>
```
using the alternative text computation tool:
https://whatsock.github.io/w3c-alternative-text-computation/Editable%20Live%20Input%20AccName%20Test.html

shows no accessible name. As a element listed under Forms:
https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-progress-element

I would expect the computation of the acc name to fall under §4.1.7 of the Accessible Name Computation:
https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#the-progress-element
where item 2 says to use the label.

Other places imply that label can be used if there is a role=progressbar
https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/

but this seems to both be redundant and also makes no apparent difference in the calculated output of the accessible name. Am I missing something important or is this just a bug?

**Comment by accdc** [comment]
This is just a bug. I'll add this to my todo list to update the live algorithm to account for this.

**Comment by accdc** [comment]
Thanks again, this should now be fixed.
